### PR TITLE
Adjust to AE2 api changes

### PR DESCRIPTION
**Pull request by Demiu**
related to GTNewHorizons/Applied-Energistics-2-Unofficial#536

### CODE REVIEW

**Review by OneEyeMaker — APPROVED** [review]

**Comment by AnrDaemon** [comment]
Ain't it better to add missing machines to AE2FC and forget ExC2 exists?

**Comment by Demiu** [comment]
@AnrDaemon maybe ¯\\\_(ツ)_/¯ this change is just so ExC2 compiles

**Comment by Dream-Master** [comment]
We not use it in gtnh anymore because ec now in ae2fc mod but I can make a version for people not play gtnh

**Comment by Demiu** [comment]
@Dream-Master ah, I see that the last commit was 4 month ago. I thought this was still in active development because repository wasn't archived.

The check fails on
`Caused by: java.lang.ClassNotFoundException: it.unimi.dsi.fastutil.objects.Object2ObjectArrayMap`

Not sure how to deal with this, `it.unimi.dsi.fastutil` is part of gtnhlib, which I see is getting downloaded in build. Maybe someone more knowledgeable about the build-and-test check can shine some light

**Comment by Demiu** [comment]
Crash on startup should be fixed by GTNewHorizons/Applied-Energistics-2-Unofficial/pull/540

**Comment by Dream-Master** [comment]
@Demiu still not build

**Pull request merged**
