### PR TITLE
Drastically improve Fluid Storage Bus performance

### PR DESCRIPTION
**Pull request by PanSzelescik**
Zrzut ekranu 2020-12-29 181955

This could even cause a 2 minute lag!

### CODE REVIEW

**Comment by repo-alt** [comment]
Judging by the git blame that weird logic was introduced to fix bug https://github.com/ExtraCells/ExtraCells2/issues/142, but description there is insufficient. So I wonder just what will break after that fix...

**Comment by bartimaeusnek** [comment]
@repo-alt seems like a duct-tape fix for not filling shit imo

**Comment by repo-alt** [comment]
That much is obvious, I'm curious just _what_ shit

**Comment by Glease** [comment]
Probably ender conduit compat. 

If filled2 is positive on second or later invocation it basically means the tank/machine consumed some fluid inside its `fill` method. AFAIK no gregtech metatileentity will do this. Can you show the full stacktrace instead of truncating stuff below GT_MetaTileEntity_BasicTank?

BTW the only "thing" so far that I know will do this is ender conduit, which is really not a tank after all. However this doesn't match the stacktrace.

**Comment by kaziu687** [comment]
We've found that this do while loop was causing 3 minute server freezes in some situations. Server thread was waiting for that loop to finnish so long:

```
Server thread" #19 prio=5 os_prio=0 tid=0x00007fd8551e5800 nid=0x2ff0a runnable [0x00007fd747ffc000]
   java.lang.Thread.State: RUNNABLE
	at gregtech.api.metatileentity.implementations.GT_MetaTileEntity_BasicTank.fill(GT_MetaTileEntity_BasicTank.java:190)
	at gregtech.api.metatileentity.MetaTileEntity.fill_default(MetaTileEntity.java:726)
	at gregtech.api.metatileentity.MetaTileEntity.fill(MetaTileEntity.java:738)
	at gregtech.api.metatileentity.BaseMetaTileEntity.fill(BaseMetaTileEntity.java:1869)
	at extracells.inventory.HandlerPartStorageFluid.injectItems(HandlerPartStorageFluid.java:199)
	at extracells.inventory.HandlerPartStorageFluid.injectItems(HandlerPartStorageFluid.java:29)
	at appeng.me.storage.NetworkInventoryHandler.injectItems(NetworkInventoryHandler.java:106)
	at appeng.me.cache.NetworkMonitor.injectItems(NetworkMonitor.java:151)
	at extracells.tileentity.TileEntityFluidInterface.fillToNetwork(TileEntityFluidInterface.java:313)
	at extracells.tileentity.TileEntityFluidInterface.fill(TileEntityFluidInterface.java:283)
	at gregtech.api.metatileentity.implementations.GT_MetaPipeEntity_Fluid.distributeFluid(GT_MetaPipeEntity_Fluid.java:327)
	at gregtech.api.metatileentity.implementations.GT_MetaPipeEntity_Fluid.onPostTick(GT_MetaPipeEntity_Fluid.java:241)
	at gregtech.api.metatileentity.BaseMetaPipeEntity.updateEntity(BaseMetaPipeEntity.java:290)
	at net.minecraft.world.World.updateEntities(World.java:2583)
	at net.minecraft.world.WorldServer.updateEntities(WorldServer.java:673)
	at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:986)
	at net.minecraft.server.dedicated.DedicatedServer.updateTimeLightAndEntities(DedicatedServer.java:432)
	at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:841)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:693)
	at java.lang.Thread.run(Thread.java:748)

**Comment by PanSzelescik** [comment]
This is full spark: https://spark.lucko.me/#WrLOsJxV5x
There is nothing after GT_MetaTileEntity_BasicTank.fill()

While loop is unnecessary because with while loop everything happens **in one tick**! So if Fluid Storage Bus can't insert the liquid let him try in the next tick instead of the same.

**Review by Glease — APPROVED** [review]
I have personally never seen this before. Perhaps some sort of werid cover/machine/whatever combination will make it go wild. In any sense, a while loop for filling fluid is bad, I'd approve this change.

**Pull request merged**
