### PR TITLE
yeet walrus

### PR DESCRIPTION
**Pull request by mitchej123**
Lewis said he hated it.;

but seriously it's 100x as big as every other texture.  :roll_eyes:

### CODE REVIEW

**Comment by GTNH-Colen** [comment]
Moment of silence for walrus 🙏

**Comment by boubou19** [comment]
🙏

**Comment by mitchej123** [comment]
image

**Comment by bombcar** [comment]
you broke the walrus and the build

how bout replace it with tiny walrus.png

then walrus afficinados can load it via a resource pack

**Pull request closed without merging**
