### PR TITLE
fix dupe of the fluid compents

### PR DESCRIPTION
**Pull request by GlodBlock**
the fluid compents will output any fluid inifnity with a special setup

### CODE REVIEW

**Review by repo-alt — COMMENTED** [review]
If that fix is working then it means that FluidRegistry.getFluid(fluidId) is not the same as fluid in current stack, which means it is broken elsewhere?

**Comment by GlodBlock** [comment]
sorry i mistook something. the bug is rooted in remote io instead of ec2

**Comment by Glease** [comment]
Yeah great. Remote IO, again.

**Comment by repo-alt** [comment]
RemoteIO is very close to EC2 in code quality, so no wonder that they work great together.

**Pull request closed without merging**
